
#define UIDS_START_RANGE 20000

enum Bg_Teams_t
{
	BATTLEGROUND_TEAM_NONE = 0,
	BATTLEGROUND_TEAM_ONE,
	BATTLEGROUND_TEAM_TWO
};

enum DarghosUids
{
    BATTLEGROUND_TEAM_1_SPAWN = UIDS_START_RANGE + 500,
    BATTLEGROUND_TEAM_2_SPAWN,
	BATTLEGROUND_LEAVE_POINT
};
