#ifndef __DARGHOS_CONST__
#define __DARGHOS_CONST__

#define UIDS_START_RANGE 20000
#define STORAGES_START_RANGE 55000

enum BattlegrondRetValue
{
	BATTLEGROUND_NO_ERROR = 0,
	BATTLEGROUND_CLOSED,
	BATTLEGROUND_CAN_NOT_LEAVE_OR_JOIN
};

enum Bg_Teams_t
{
	BATTLEGROUND_TEAM_NONE = 0,
	BATTLEGROUND_TEAM_ONE,
	BATTLEGROUND_TEAM_TWO
};

enum DarghosUids
{
    BATTLEGROUND_TEAM_1_SPAWN = UIDS_START_RANGE + 500,
    BATTLEGROUND_TEAM_2_SPAWN,
	BATTLEGROUND_LEAVE_POINT
};

enum DarghosPlayerStorageIds
{
	DARGHOS_STORAGE_LAST_BATTLEGROUND_LEAVE = STORAGES_START_RANGE,
	DARGHOS_STORAGE_LAST_BATTLEGROUND_JOIN
};

enum DarghosPvpTypes
{
	PVP_SIMPLE_BATTLEGROUND = 0,
	PVP_ARENA_1X1
};

#endif