#ifdef __DARGHOS_CUSTOM__
#ifndef __DARGHOS_CONST__
#define __DARGHOS_CONST__

#define UIDS_START_RANGE 20000
#define STORAGES_START_RANGE 55000

#define DUNGEON_5_PEOPLE 5
#define DUNGEON_10_PEOPLE 10
#define DUNGEON_20_PEOPLE 20

#endif
#endif
