#ifdef __DARGHOS_CUSTOM__
#ifndef __DARGHOS_ENUMS__
#define __DARGHOS_ENUMS__

enum DungeonState_t
{
    DUNGEON_STATE_FREE = 0,
    DUNGEON_STATE_BUSY,
    DUNGEON_STATE_CLOSED
}

enum SlotTemplateRule_t
{
    SLOT_TEMPLATE_NONE = 0,
    SLOT_TEMPLATE_DUNGEON_5_PEOPLE
}

enum Role_t
{
    ROLE_NONE = 0,
    ROLE_DEFENSER,
    ROLE_ATTACKER,
    ROLE_HEALER
}

enum BattlegroundStatus
{
	BUILDING_TEAMS = 0,
	PREPARING,
	STARTED,
	FINISHED
};

enum BattlegroundFinishBy
{
	BattlegroundFinishByTime = 0,
	BattlegroundFinishByPoints
};

enum BattlegrondRetValue
{
	BATTLEGROUND_NO_ERROR = 0,
	BATTLEGROUND_CLOSED,
	BATTLEGROUND_CAN_NOT_JOIN,
	BATTLEGROUND_PUT_IN_WAITLIST,
	BATTLEGROUND_PUT_INSIDE,
	BATTLEGROUND_PUT_DIRECTLY,
	BATTLEGROUND_ALREADY_IN_WAITLIST,
	BATTLEGROUND_INFIGHT
};

enum Bg_Teams_t
{
	BATTLEGROUND_TEAM_NONE = 0,
	BATTLEGROUND_TEAM_ONE,
	BATTLEGROUND_TEAM_TWO
};

enum DarghosUids
{
    BATTLEGROUND_TEAM_1_SPAWN = UIDS_START_RANGE + 500,
    BATTLEGROUND_TEAM_2_SPAWN,
	BATTLEGROUND_TEAM_1_WALL_START,
	BATTLEGROUND_TEAM_1_WALL_2,
	BATTLEGROUND_TEAM_1_WALL_3,
	BATTLEGROUND_TEAM_1_WALL_END,
	BATTLEGROUND_TEAM_2_WALL_START,
	BATTLEGROUND_TEAM_2_WALL_2,
	BATTLEGROUND_TEAM_2_WALL_3,
	BATTLEGROUND_TEAM_2_WALL_END,
};

enum DarghosPlayerStorageIds
{
	DARGHOS_STORAGE_BATTLEGROUND_DESERTER_UNTIL = STORAGES_START_RANGE
};

enum DarghosPvpTypes
{
	PVP_SIMPLE_BATTLEGROUND = 0,
	PVP_ARENA_1X1
};

#endif
#endif
